### ISSUE TITLE
New parallel array for required min ver of deb dep. fails, included package not installed when needed

### ISSUE THREAD

**Issue by esaude-ops** [esaude/installer#9]
Testing with fresh install of 16.04.0 and 1.0.0-rc.2

dpkg --compare-versions complains about needing 3 args (some arg is null)

**Comment by kml27** [comment]
Fixed completed in 1.0.2
- if now checks if [ $? -ne 0 ]; after compare_versions (error code was 2)
- changed $xenial and bionic docker_depends versions array from var=$arr to var=(${arr[*]})
